import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Home, Wind, AlertTriangle } from 'lucide-react';
export const NotFoundPage = () => {
    const navigate = useNavigate();
    return (_jsx("div", { className: "min-h-screen flex items-center justify-center p-6", children: _jsxs("div", { className: "text-center max-w-md mx-auto", children: [_jsx(motion.div, { initial: { opacity: 0, scale: 0.5 }, animate: { opacity: 1, scale: 1 }, transition: { duration: 0.6, type: 'spring', bounce: 0.4 }, className: "mb-8", children: _jsxs("div", { className: "relative inline-block", children: [_jsx("div", { className: "w-32 h-32 rounded-full flex items-center justify-center mx-auto", style: { background: 'linear-gradient(135deg, rgba(0,212,255,0.1), rgba(139,92,246,0.1))', border: '2px solid rgba(0,212,255,0.2)' }, children: _jsx(motion.div, { animate: { rotate: [0, 5, -5, 0] }, transition: { repeat: Infinity, duration: 4, ease: 'easeInOut' }, children: _jsx(Wind, { className: "w-16 h-16 text-cyan-400 opacity-80" }) }) }), _jsx("div", { className: "absolute -top-2 -right-2 w-8 h-8 rounded-full bg-orange-500/20 border border-orange-500/30 flex items-center justify-center", children: _jsx(AlertTriangle, { className: "w-4 h-4 text-orange-400" }) })] }) }), _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.2 }, children: [_jsx("h1", { className: "text-8xl font-bold font-display neon-text mb-2", children: "404" }), _jsx("h2", { className: "text-xl font-semibold text-white mb-3", children: "Page Not Found" }), _jsx("p", { className: "text-slate-400 text-sm leading-relaxed mb-8", children: "The air quality data you're looking for seems to have drifted away. This page doesn't exist or may have been moved." })] }), _jsxs(motion.button, { initial: { opacity: 0, y: 10 }, animate: { opacity: 1, y: 0 }, transition: { delay: 0.4 }, onClick: () => navigate('/dashboard'), className: "btn-primary inline-flex items-center gap-2 text-sm", children: [_jsx(Home, { className: "w-4 h-4" }), "Back to Dashboard"] })] }) }));
};
export default NotFoundPage;
